spring.application.name=rubrica

# specificare timeout di connessione per hikari (nel caso di container Spring)

# caricamento nelle variabili d'ambiente
spring.datasource.url=jdbc:mysql://${DB_HOST:lolalhost}:3306/${DB_NAME:rubrica_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# configurazionei per JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true

# Configurazioni del framework