# serve semore se abbiamo app Springboot
spring.application.name=rubrica

# specificare timeout di connessione per hikari (nel caso di container Spring)

# setup connessione database --> servono solo se abbiamo un app con container
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:rubrica_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# configurazionei per JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true

# Configurazioni del framework (impostazioe sul redirect)
server.forward-headers-strategy=framework